### ISSUE TITLE
The color conundrum

### ISSUE THREAD

**Issue by Kwonunn** [Blender-PLY-Project/blender#165]
What happens when exporting two objects with colors enabled when one has a color layer and the other doesn't?

Your mission is to find out, and to mitigate the damage.

Good luck Agent P

**Comment by Stroopwafe1** [comment]
This is why the PLY spec is meant for only one object, I refer back to [this line](http://paulbourke.net/dataformats/ply/#:~:text=A%20PLY%20file%20contains%20the%20description%20of%20exactly%20one%20object.)

**Comment by Stroopwafe1** [comment]
It's a more interesting problem where an object is only partly coloured. How do we export this? With colour set to 0,0,0,0?

**Comment by Kwonunn** [comment]
I know the ply spec really isn't meant for this but we should still account for it since we do allow exporting multiple objects.

How does one partially color an object? I thought the color layer would apply to the entire object at once?

**Comment by Nathan-Rozendaal** [comment]
Hans Goudy already suggested a fix in the feedback he gave yesterday
``` 
if (export_params.export_colors) {
  const StringRef name = mesh->active_color_attribute;
  if (!name.is_empty()) {
    const bke::AttributeAccessor attributes = mesh->attributes();
    const VArray<ColorGeometry4f> attribute = attributes.lookup_or_default<ColorGeometry4f>(
        name, ATTR_DOMAIN_POINT, {0.0f, 0.0f, 0.0f, 0.0f});
    /* export color data like before */
  }
}
```

**Comment by Stroopwafe1** [comment]
Ignore my last comment, I forgot when you add the colour layer, every vertex gets a colour.

**Comment by Kwonunn** [comment]
I didn't realize that code was going to fix this issue, I'm going to implement that when I get to that issue. I'll see how it works
