### ISSUE TITLE
Importing PLY files with a color layer doesn't select the layer as active after importing

### ISSUE THREAD

**Issue by Kwonunn** [Blender-PLY-Project/blender#166]
Steps:

Export a ply file with some color

Import it again

If you now try to shade the object with it's Color Attribute nothing happens

You first have to manually select the layer as active in the mesh properties panel:
![image](https://user-images.githubusercontent.com/39026963/216327714-2ad7dbcf-6870-4eac-b1ba-4dfe1fde7d68.png)

**Comment by Stroopwafe1** [comment]
Yeah, Blender adds its own attribute on the face corners. Sadly Hans Goudey didn't say how we can solve this problem with the importer.

**Comment by Kwonunn** [comment]
That's a shame.

If you don't have any ideas you can close the issue I guess

**Comment by Stroopwafe1** [comment]
Found a function that might do the trick: `BKE_id_attributes_active_color_set(&mesh->id, "Col");` Gonna try it
