### ISSUE TITLE
Objects aren't offset properly when exporting/importing

### ISSUE THREAD

**Issue by Kwonunn** [Blender-PLY-Project/blender#167]
Objects whose origins aren't on the world origin are offset incorrectly when exporting/importing

![image](https://user-images.githubusercontent.com/39026963/216328183-6bafc4ed-2b5d-415f-983a-d9af0a125430.png)
left: the original object, right: the object after importing/exporting

**Comment by Stroopwafe1** [comment]
Oops, closed wrong one

**Comment by Kwonunn** [comment]
Closed by #170
