### ISSUE TITLE
When 2 or more objects get exported, the vertex indices for the face list get messed up

### ISSUE THREAD

**Issue by Nathan-Rozendaal** [Blender-PLY-Project/blender#29]
How to reproduce:
1. Have 2 or more unique objects in the scene (high poly count makes the issue more apparent)
2. Export as PLY file 
3. Import the PLY file

Possible fix:
1. Export object
2. Add vertex amount of that object to a variable
3. Use that variable to offset the vertex index
4. Repeat

**Comment by bashendriks10** [comment]
isn't this fixed already?

**Comment by Nathan-Rozendaal** [comment]
@Kwonunn!!

**Comment by Kwonunn** [comment]
Yes, it's fixed. I didn't know you made an issue out of this.
