### ISSUE TITLE
Use float buffer[3] instead of the expensive std::vector for each vertex.

### ISSUE THREAD

**Issue by bashendriks10** [Blender-PLY-Project/blender#45]
Ply_file_buffer_binary.hh line 37-40
Write out all 3 values at once using a single float buffer[3] stack variable or similar. There should be no need to create an expensive std::vector for each vertex… This function causes a lot of memory allocation and movement which shows up profiles.

**Comment by Kwonunn** [comment]
Dit is ergens in de tussentijd vervangen met efficientere code, niet meer nodig.
